import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ModeIcon from "@/components/ModeIcon";
import { ThemeProvider } from "@/context/ThemeContext";

// Mevcut fontlar
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Yeni fontlar
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400"], // Lazım olan çəki dəyərlərini əlavə et
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400"],
});
const montserratBold = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserratBold.variable} ${roboto.variable} ${montserrat.variable} antialiased `}
      >
        <ThemeProvider>
          <div className="mx-auto px-[20px] md:px-[70px]">
            <Header />
            {children}
            <ModeIcon />
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
